import type { ServiceItem } from '@/types/service';

export const serviceCatalog: ServiceItem[] = [
  {
    id: 'registry',
    title: 'Registry',
    description: 'Property registration, title verification, and document drafting support.',
    price: '₹4,999',
    category: 'Registry',
    serviceType: 'Registry',
    estimatedTurnaround: '3-5 business days',
    includes: ['Title verification', 'Drafting support', 'Registration guidance'],
    featured: true,
    icon: 'document-text-outline',
  },
  {
    id: 'property-mutation',
    title: 'Property Mutation',
    description: 'Ownership transfer and mutation workflow support with legal review.',
    price: '₹6,499',
    category: 'Property Mutation',
    serviceType: 'Property Mutation',
    estimatedTurnaround: '5-8 business days',
    includes: ['Mutation filing guidance', 'Ownership transfer review', 'Municipal process support'],
    featured: true,
    icon: 'home-outline',
  },
  {
    id: 'registered-will',
    title: 'Registered Will',
    description: 'Will drafting, registration guidance, and legal validation support.',
    price: '₹7,999',
    category: 'Registered Will',
    serviceType: 'Registered Will',
    estimatedTurnaround: '4-7 business days',
    includes: ['Will drafting support', 'Documentation checklist', 'Registration process guidance'],
    icon: 'document-text-outline',
  },
  {
    id: 'registry-land-verification',
    title: 'Registry & Land Verification',
    description: 'Land registry checks, title diligence, and transaction readiness review.',
    price: '₹2,999',
    category: 'Registry & Land Verification',
    serviceType: 'Registry & Land Verification',
    estimatedTurnaround: '2-4 business days',
    includes: ['Land records review', 'Title diligence', 'Risk flags report'],
    icon: 'shield-checkmark-outline',
  },
  {
    id: 'marriage-registration',
    title: 'Marriage Registration',
    description: 'End-to-end support for marriage registration process and compliance.',
    price: '₹1,999',
    category: 'Marriage Registration',
    serviceType: 'Marriage Registration',
    estimatedTurnaround: '2-3 business days',
    includes: ['Eligibility and document checks', 'Form preparation support', 'Registration appointment guidance'],
    icon: 'briefcase-outline',
  },
  {
    id: 'birth-certificate',
    title: 'Birth Certificate',
    description: 'Assistance for new applications, corrections, and record retrieval.',
    price: '₹5,999',
    category: 'Birth Certificate',
    serviceType: 'Birth Certificate',
    estimatedTurnaround: '4-6 business days',
    includes: ['Application drafting help', 'Correction support', 'Submission guidance'],
    icon: 'document-text-outline',
  },
  {
    id: 'challan-payment',
    title: 'Challan Payment',
    description: 'Legal guidance for challans, penalties, and closure documentation.',
    price: '₹3,499',
    category: 'Challan Payment',
    serviceType: 'Challan Payment',
    estimatedTurnaround: '1-2 business days',
    includes: ['Violation review', 'Payment path guidance', 'Closure proof checklist'],
    icon: 'briefcase-outline',
  },
  {
    id: 'agreement-registration',
    title: 'Agreement Registration',
    description: 'Registration support for agreements, deeds, and legal contracts.',
    price: '₹2,499',
    category: 'Agreement Registration',
    serviceType: 'Agreement Registration',
    estimatedTurnaround: '2-4 business days',
    includes: ['Draft review support', 'Stamp duty guidance', 'Registration filing support'],
    icon: 'document-text-outline',
  },
  {
    id: 'affidavit',
    title: 'Affidavit',
    description: 'Affidavit drafting and notarization workflow for legal needs.',
    price: '₹9,999',
    category: 'Affidavit',
    serviceType: 'Affidavit',
    estimatedTurnaround: '1-3 business days',
    includes: ['Affidavit drafting', 'Notarization checklist', 'Submission guidance'],
    icon: 'document-text-outline',
  },
  {
    id: 'consultation',
    title: 'Consultation',
    description: 'Personalized legal consultation sessions with practice-area specialists.',
    price: '₹4,499',
    category: 'Consultation',
    serviceType: 'Consultation',
    estimatedTurnaround: 'Within 24 hours',
    includes: ['Case intake summary', 'Expert consultation call', 'Action-oriented legal recommendations'],
    featured: true,
    icon: 'briefcase-outline',
  },
  {
    id: 'fir-igrs-complaint',
    title: 'FIR or IGRS Complaint',
    description: 'Legal guidance for complaint filing, documentation, and response strategy.',
    price: '₹5,499',
    category: 'FIR or IGRS Complaint',
    serviceType: 'FIR or IGRS Complaint',
    estimatedTurnaround: '2-5 business days',
    includes: ['Complaint drafting support', 'Evidence checklist', 'Submission strategy'],
    icon: 'shield-checkmark-outline',
  },
  {
    id: 'caste-certificate',
    title: 'Caste Certificate',
    description: 'Application and correction support for caste certification workflows.',
    price: '₹1,999',
    category: 'Caste Certificate',
    serviceType: 'Caste Certificate',
    estimatedTurnaround: '2-4 business days',
    includes: ['Document checklist', 'Form support', 'Verification guidance'],
    icon: 'document-text-outline',
  },
  {
    id: 'residence-domicile-certificate',
    title: 'Residence / Domicile Certificate',
    description: 'Guidance for residence and domicile certificate filing and updates.',
    price: '₹1,999',
    category: 'Residence / Domicile Certificate',
    serviceType: 'Residence / Domicile Certificate',
    estimatedTurnaround: '2-4 business days',
    includes: ['Residence proof review', 'Application support', 'Submission follow-up checklist'],
    icon: 'home-outline',
  },
  {
    id: 'income-certificate',
    title: 'Income Certificate',
    description: 'Support for income certificate applications and corrections.',
    price: '₹1,999',
    category: 'Income Certificate',
    serviceType: 'Income Certificate',
    estimatedTurnaround: '2-4 business days',
    includes: ['Income proof checklist', 'Application drafting support', 'Submission guidance'],
    icon: 'briefcase-outline',
  },
];

export const getServiceById = (id?: string) => serviceCatalog.find((service) => service.id === id);
